### ISSUE TITLE
Problem loading provided CMC weights for training linear classifier

### ISSUE THREAD

**Issue by EliSchwartz** [HobbitLong/PyContrast#1]
The function load_encoder_weights assumes the pretrained checkpoint state_dict has the structure "module.encoder.*", for CMC it's "module.encoder1.*" and "module.encoder2.*". I verified it's not the case for MoCo and InfoMin, didn't check other models.

**Comment by HobbitLong** [comment]
@EliSchwartz , Thank you for spotting this error. Fixed now!
