### ISSUE TITLE
classifier weights for pre-trained models

### ISSUE THREAD

**Issue by kantharajucn** [HobbitLong/PyContrast#17]
Hello @HobbitLong 

Thanks for the great work!
We want to use your pre-trained models  using  resnet50 architecture in out toolkit. Would it be possible to release weights for the classifier?  

Best,
Kantharaju.

**Comment by HobbitLong** [comment]
Hi, @kantharajucn, which toolkit?

**Comment by kantharajucn** [comment]
Hi @HobbitLong 

We are building a generalization benchmark to compare Machines vs Humans.

Best,
Kantharaju
