### ISSUE TITLE
Proposition A.1 

### ISSUE THREAD

**Issue by liun-online** [HobbitLong/PyContrast#2]
thanks your paper, and I think it's a fundamental job!
 But, I'm not clear that why I(y; x) = I(y; v1, v2) as given in proof in Proposition A.1. Could you please show me the reliable reason for it? Maybe, it's a naive question.
I'm hope for your reply!
Best wishes!

**Comment by HobbitLong** [comment]
Hi, @liun-online,

Thanks for your kind word.
(1) I(y; x) >= I(y; v1, v2), as v1, v2 are functions of x, so we have this by data processing inequality;
(2) I(y; v1, v2) >= I(y; v1) = I(y; x), as assumption.
So it's equal. 

Let me know if I am wrong or if you have further questions. I will close it by now but feel free to reopen.

**Comment by HobbitLong** [comment]
Sorry I feel like I should have a separate repo for "infomin" [[paper]](https://arxiv.org/abs/2005.10243v1) so paper specific questions can be asked there. 

I will do this in the future, to release my code about the "unsupervised" and "semi-supervised" view learning part shown in the [paper](https://arxiv.org/abs/2005.10243v1).
