### ISSUE TITLE
How to structure dataset?

### ISSUE THREAD

**Issue by GiuseppePennisi** [HobbitLong/PyContrast#25]
Hello,
I apologize for the newbie question.
i'm trying to do some experiment with this repo, and in particular, I'd like to try instance discrimination. I analyzed [ImageFolderInstance]( https://github.com/HobbitLong/PyContrast/blob/master/pycontrast/datasets/dataset.py) but I'm not sure how to structure my dataset. In the specific case (instance discrimination), should I create a dataset folder which contains folders  with only one image ( in other case, a single class associated to a single image, as described in the paper) or it's enough only have a folder which contains all images of my dataset and so, the instance discrimination is based directly on the index returned by ImageFolderInstance.
Just to be more clear:
First Structure:

- Dataset
    - image_1_folder
        -image_1.jpg
    - image_2_folder
        -image_2.jpg
    - image_3_folder
        -image_3.jpg

Second Structure
- Dataset
    -image_1.jpg
    -image_2.jpg
    -image_3.jpg
    
Thanks for the help.

**Comment by HobbitLong** [comment]
Hi, @GiuseppePennisi,

Both should work. In your first case, directly pass the path of `Dataset` to the loader, while in your second case, you need to pass the path of up-level directory of `Dataset`.
