### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by jp7c5** [HobbitLong/PyContrast#4]
Thanks for sharing this nice work!
Since it seems that currently no license is specified, would you mind updating license for this repo?

**Comment by HobbitLong** [comment]
Hi, @jp7c5,

I have put the license [here](https://github.com/HobbitLong/PyContrast/blob/master/pycontrast/LICENSE).

**Comment by jp7c5** [comment]
I checked it. Thanks again, @HobbitLong!
