### ISSUE TITLE
Configs issues about "Res5ROIHeadsExtraNorm"

### ISSUE THREAD

**Issue by Kevinz-code** [HobbitLong/PyContrast#40]
Hi, thanks so much for providing the detection configs.

When I run detectron2 based on "Base-RCNN-C4-BN.yaml", the process said that "Res5ROIHeadsExtraNorm" has not been registered?

And I carefully read the documents of detectron2,
it has 'Res5ROIHeads', but does not have 'Res5ROIHeadsExtraNorm'.

Does Res5ROIHeads ==  Res5ROIHeadsExtraNorm?

**Comment by HobbitLong** [comment]
see [here](https://github.com/facebookresearch/moco/blob/main/detection/train_net.py)

**Comment by Kevinz-code** [comment]
Thank you so much for your timely reply, Looking forward to your excellent works in the future!
